export const sectionVals = {
    "All": 'home',
    "Arts": 'arts',
    "Automobiles": 'automobiles',
    "Books": 'books',
    "Business": 'business',
    "Fashion": 'fashion',
    "Food": 'food',
    "Health": 'health',
    "Insider": 'insider',
    "Magazine": 'magazine',
    "NY Region": 'nyregion',
    "Obituaries": 'obituaries',
    "Opinion": 'opinion',
    "Politics": 'politics',
    "Real Estate": 'realestate',
    "Science": 'science',
    "Sports": 'sports',
    "Sunday Review": 'sundayreview',
    "Technology": 'technology',
    "Theater": 'theater',
    "Times Magazine": 't-magazine',
    "Travel": 'travel',
    "Upshot": 'upshot',
    "U.S.": 'us',
    "World": 'world'
}